package com.pmar.kotlinlab.projecteuler

/**
 * @author Pavel Marchenko (Pavel.Marchenko@datart.com -- DataArt)
 */
class Problem12 : Problem<Long>() {
    override fun getProblemId() = 12

    override fun getProblemDesc() =
        """
            The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
            What is the value of the first triangle number to have over five hundred divisors?
        """.trimIndent()

    override fun solve() = (1L..Long.MAX_VALUE).first { it.triangleNumber().divisors().size >= 500 }.triangleNumber()

}